/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 OK when the service is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/difficulties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List difficulty tiers
         * @description Returns all available quiz difficulty tiers derived from DIFFICULTY_TIERS.
         *     No LLM call is made. Useful for populating a difficulty picker in the UI.
         */
        get: operations["get_difficulties_quiz_difficulties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a quiz
         * @description Generates a multiple-choice quiz on the given topic using the RAG pipeline.
         *     - 503 if the chain cannot be initialised (missing API key, ChromaDB unavailable).
         *     - 500 if the LLM call or JSON parsing fails after the fallback retry.
         */
        post: operations["generate_quiz_quiz_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest documents into ChromaDB
         * @description Accepts one or more documents and runs the full ingestion pipeline:
         *     load → split → tag → embed → store in ChromaDB.
         *     Supported types: .txt, .docx, .ipynb, .py
         *     - 422 if any file has an unsupported extension.
         *     - 500 if the ingestion pipeline fails.
         *     Temp files are always cleaned up regardless of outcome.
         */
        post: operations["upload_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate-world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate game world from ChromaDB
         * @description Reads ChromaDB metadata and groups chunks by topic_cluster into game zones.
         *     Each zone's enemy_tier is determined by the dominant difficulty_tier of its chunks.
         *     No LLM call is made — this is a pure metadata operation.
         *     - 503 if ChromaDB is unavailable.
         */
        post: operations["generate_world_generate_world_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available zones
         * @description Returns a sorted list of unique zone names (topic_cluster values) in ChromaDB.
         *     Excludes 'unclassified'. No LLM call is made.
         *     - 503 if ChromaDB is unavailable.
         */
        get: operations["get_zones_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a combat encounter question
         * @description Generates a single quiz question using the RAG pipeline, filtered to chunks
         *     belonging to the requested zone (topic_cluster).
         *     - 404 if the zone does not exist in ChromaDB.
         *     - 503 if the chain cannot be initialised.
         *     - 500 if the LLM call fails.
         */
        post: operations["encounter_encounter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate player answer
         * @description Compares the player's answer to the correct answer (case-insensitive).
         *     Returns XP/HP deltas based on difficulty:
         *       Correct → xp_delta = difficulty reward, hp_delta = 0
         *       Wrong   → xp_delta = 0, hp_delta = -difficulty penalty
         *     No LLM call or database access is made.
         */
        post: operations["answer_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerRequest
         * @description Player's answer to an encounter question.
         * @example {
         *       "correct_answer": "A",
         *       "difficulty": "medium",
         *       "explanation": "RAG stands for Retrieval-Augmented Generation.",
         *       "player_answer": "A",
         *       "question": "What does the 'R' in RAG stand for?"
         *     }
         */
        AnswerRequest: {
            /**
             * Question
             * @description The question text (echoed for UI display)
             */
            question: string;
            /**
             * Correct Answer
             * @description Expected answer key, e.g. "A"
             */
            correct_answer: string;
            /**
             * Player Answer
             * @description Player's chosen answer key, e.g. "B"
             */
            player_answer: string;
            /**
             * Difficulty
             * @description Difficulty tier — determines XP/HP delta magnitude
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Explanation
             * @description Explanation text echoed back for UI display
             * @default
             */
            explanation: string;
        };
        /**
         * AnswerResponse
         * @description Result of evaluating the player's answer.
         * @example {
         *       "correct": true,
         *       "difficulty": "medium",
         *       "explanation": "RAG stands for Retrieval-Augmented Generation.",
         *       "hp_delta": 0,
         *       "xp_delta": 20
         *     }
         */
        AnswerResponse: {
            /**
             * Correct
             * @description True if player_answer matches correct_answer (case-insensitive)
             */
            correct: boolean;
            /**
             * Xp Delta
             * @description XP gained: 10/20/30 for easy/medium/hard on correct; 0 on wrong
             */
            xp_delta: number;
            /**
             * Hp Delta
             * @description HP change: 0 on correct; -10/-20/-30 for easy/medium/hard on wrong
             */
            hp_delta: number;
            /**
             * Difficulty
             * @description Echoed difficulty tier
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Explanation
             * @description Echoed explanation text for display in the UI
             */
            explanation: string;
        };
        /** Body_upload_documents_upload_post */
        Body_upload_documents_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * DifficultiesResponse
         * @description All available difficulty tiers.
         */
        DifficultiesResponse: {
            /**
             * Difficulties
             * @description All three difficulty tiers in order: easy, medium, hard
             */
            difficulties: components["schemas"]["DifficultyInfo"][];
        };
        /**
         * DifficultyInfo
         * @description Metadata for a single difficulty tier.
         */
        DifficultyInfo: {
            /**
             * Key
             * @description Difficulty key used in requests
             * @enum {string}
             */
            key: "easy" | "medium" | "hard";
            /**
             * Label
             * @description Display label, e.g. "Tier 1 – Slime-level"
             */
            label: string;
            /**
             * Description
             * @description Bloom's taxonomy guidance for this tier
             */
            description: string;
        };
        /**
         * EncounterRequest
         * @description Parameters to generate a single combat encounter question.
         * @example {
         *       "difficulty": "medium",
         *       "zone": "RAG Architecture"
         *     }
         */
        EncounterRequest: {
            /**
             * Zone
             * @description Zone name (topic_cluster) to filter ChromaDB retrieval
             */
            zone: string;
            /**
             * Difficulty
             * @description Bloom's taxonomy difficulty tier
             * @default medium
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
        };
        /**
         * EncounterResponse
         * @description A single combat encounter question.
         * @example {
         *       "answer": "A",
         *       "difficulty": "medium",
         *       "explanation": "RAG stands for Retrieval-Augmented Generation.",
         *       "options": {
         *         "A": "Retrieval",
         *         "B": "Recursive",
         *         "C": "Relational"
         *       },
         *       "question": "What does the 'R' in RAG stand for?",
         *       "zone": "RAG Architecture"
         *     }
         */
        EncounterResponse: {
            /**
             * Zone
             * @description Zone this question was generated for
             */
            zone: string;
            /**
             * Difficulty
             * @description Difficulty tier of this encounter
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Question
             * @description The question text
             */
            question: string;
            /**
             * Options
             * @description Answer options keyed by letter, e.g. {"A": "...", "B": "..."}
             */
            options: {
                [key: string]: string;
            };
            /**
             * Answer
             * @description Letter key of the correct answer
             */
            answer: string;
            /**
             * Explanation
             * @description Explanation of the correct answer
             */
            explanation: string;
        };
        /**
         * GenerateWorldResponse
         * @description All zones generated from ChromaDB metadata.
         */
        GenerateWorldResponse: {
            /**
             * Zones
             * @description All game zones sorted alphabetically by name
             */
            zones: components["schemas"]["Zone"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description API liveness response.
         * @example {
         *       "status": "ok",
         *       "version": "1.0.0"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @description Always "ok" when the service is running
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description API version string
             */
            version: string;
        };
        /**
         * QuizQuestion
         * @description A single multiple-choice quiz question.
         */
        QuizQuestion: {
            /**
             * Question Number
             * @description 1-based position of this question in the quiz
             */
            question_number: number;
            /**
             * Question
             * @description The question text
             */
            question: string;
            /**
             * Options
             * @description Answer options keyed by letter, e.g. {"A": "...", "B": "..."}
             */
            options: {
                [key: string]: string;
            };
            /**
             * Answer
             * @description Letter key of the correct answer, e.g. "A"
             */
            answer: string;
            /**
             * Explanation
             * @description Explanation of why the correct answer is right
             */
            explanation: string;
        };
        /**
         * QuizRequest
         * @description Parameters for quiz generation.
         * @example {
         *       "difficulty": "medium",
         *       "n_options": 3,
         *       "n_questions": 5,
         *       "topic": "Prompt Engineering"
         *     }
         */
        QuizRequest: {
            /**
             * Topic
             * @description Topic to generate a quiz about
             */
            topic: string;
            /**
             * Difficulty
             * @description Bloom's taxonomy difficulty tier: easy | medium | hard
             * @default medium
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * N Questions
             * @description Number of questions to generate (1–20)
             * @default 5
             */
            n_questions: number;
            /**
             * N Options
             * @description Number of answer options per question (2–5)
             * @default 3
             */
            n_options: number;
        };
        /**
         * QuizResponse
         * @description Full quiz returned by the RAG pipeline.
         * @example {
         *       "difficulty": "Tier 2 – Skeleton-level",
         *       "questions": [
         *         {
         *           "answer": "A",
         *           "explanation": "Zero-shot prompting provides no worked examples to the model.",
         *           "options": {
         *             "A": "No examples given",
         *             "B": "Many examples given",
         *             "C": "Fine-tuning the model"
         *           },
         *           "question": "What is zero-shot prompting?",
         *           "question_number": 1
         *         }
         *       ],
         *       "quiz_title": "Prompt Engineering: Tier 2 – Skeleton-level"
         *     }
         */
        QuizResponse: {
            /**
             * Quiz Title
             * @description Title of the generated quiz
             */
            quiz_title: string;
            /**
             * Difficulty
             * @description Full tier label, e.g. "Tier 2 – Skeleton-level"
             */
            difficulty: string;
            /**
             * Questions
             * @description Ordered list of quiz questions
             */
            questions: components["schemas"]["QuizQuestion"][];
        };
        /**
         * UploadResponse
         * @description Result of a document ingestion run.
         * @example {
         *       "chunks_added": 42
         *     }
         */
        UploadResponse: {
            /**
             * Chunks Added
             * @description Number of document chunks added to ChromaDB
             */
            chunks_added: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Zone
         * @description A game zone derived from a topic_cluster group in ChromaDB.
         * @example {
         *       "chunk_count": 12,
         *       "enemy_tier": "Skeleton",
         *       "name": "RAG Architecture"
         *     }
         */
        Zone: {
            /**
             * Name
             * @description Zone name — matches the topic_cluster metadata value in ChromaDB
             */
            name: string;
            /**
             * Enemy Tier
             * @description Enemy type derived from dominant difficulty_tier: Slime (beginner) | Skeleton (intermediate) | Dragon (advanced)
             * @enum {string}
             */
            enemy_tier: "Slime" | "Skeleton" | "Dragon";
            /**
             * Chunk Count
             * @description Number of document chunks belonging to this zone
             */
            chunk_count: number;
        };
        /**
         * ZonesResponse
         * @description Lightweight list of zone names currently in ChromaDB.
         * @example {
         *       "zones": [
         *         "Agents and Tools",
         *         "LangChain",
         *         "RAG Architecture"
         *       ]
         *     }
         */
        ZonesResponse: {
            /**
             * Zones
             * @description Sorted list of zone names (topic_cluster values), excluding 'unclassified'
             */
            zones: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_difficulties_quiz_difficulties_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DifficultiesResponse"];
                };
            };
        };
    };
    generate_quiz_quiz_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_world_generate_world_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateWorldResponse"];
                };
            };
        };
    };
    get_zones_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesResponse"];
                };
            };
        };
    };
    encounter_encounter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
